site_name: Cluster.tools
site_url: https://cluster.tools/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css: [/stylesheets/extra.css]
nav:
  - Home: index.md
  - Getting Started: in5min.md
  - Concepts:
    - Overview: "./concepts/overview.md"
    - Mounting: "./concepts/mounting.md"
    - Supervisors: "./concepts/supervisor.md"
    - Architecture:
      - Interfaces:
        - Cluster: "./data-structures/cluster.md"
      - Endpoints:
        - Client Endpoint: "./endpoints/client.md"
        - Processor Endpoint: "./endpoints/processor.md"
      - Components:
        - Cache: "./components/cache.md"
        - Database: "./components/database.md"
        - Messenger: "./components/messenger.md"
        - Processor: "./components/processor.md"
        - Scheduler: "./components/scheduler.md"
        - Supervisor: "./components/supervisor.md"
  - Developers:
    - How to write a Processor?: processors.md